"""align menu input database tables

Revision ID: 462a5442b523
Revises: 71c3b17239ee
Create Date: 2026-05-03 22:46:00.338664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462a5442b523'
down_revision = '71c3b17239ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_info_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('police_number', sa.String(length=20), nullable=False),
    sa.Column('nrkb', sa.String(length=20), nullable=False),
    sa.Column('frame_last_five', sa.String(length=5), nullable=False),
    sa.Column('nik', sa.String(length=32), nullable=False),
    sa.Column('result_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_info_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_info_inquiries_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_info_inquiries_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('fine_check_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('fine_id', sa.Integer(), nullable=True),
    sa.Column('police_number', sa.String(length=20), nullable=False),
    sa.Column('frame_number_input', sa.String(length=80), nullable=False),
    sa.Column('engine_number_input', sa.String(length=80), nullable=True),
    sa.Column('incident_location', sa.String(length=120), nullable=True),
    sa.Column('result_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fine_check_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fine_check_inquiries_fine_id'), ['fine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fine_check_inquiries_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fine_check_inquiries_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('tax_check_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('tax_record_id', sa.Integer(), nullable=True),
    sa.Column('nrkb', sa.String(length=20), nullable=False),
    sa.Column('frame_last_five', sa.String(length=5), nullable=False),
    sa.Column('nik', sa.String(length=32), nullable=False),
    sa.Column('result_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tax_record_id'], ['tax_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_check_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_check_inquiries_tax_record_id'), ['tax_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_check_inquiries_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_check_inquiries_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('stnk_renewal_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nrkb', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('frame_last_five', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('nik', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stnk_renewal_applications', schema=None) as batch_op:
        batch_op.drop_column('nik')
        batch_op.drop_column('frame_last_five')
        batch_op.drop_column('nrkb')

    with op.batch_alter_table('tax_check_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_check_inquiries_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_tax_check_inquiries_user_id'))
        batch_op.drop_index(batch_op.f('ix_tax_check_inquiries_tax_record_id'))

    op.drop_table('tax_check_inquiries')
    with op.batch_alter_table('fine_check_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fine_check_inquiries_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_fine_check_inquiries_user_id'))
        batch_op.drop_index(batch_op.f('ix_fine_check_inquiries_fine_id'))

    op.drop_table('fine_check_inquiries')
    with op.batch_alter_table('vehicle_info_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_info_inquiries_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_info_inquiries_user_id'))

    op.drop_table('vehicle_info_inquiries')
    # ### end Alembic commands ###
