"""initial samsatgo schema

Revision ID: 4ebfef22dc14
Revises: 
Create Date: 2026-05-03 21:32:24.585163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebfef22dc14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nik', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('frame_number', sa.String(length=80), nullable=True),
    sa.Column('engine_number', sa.String(length=80), nullable=True),
    sa.Column('stnk_number', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_frame_number'), ['frame_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_plate_number'), ['plate_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_vehicles_user_id'), ['user_id'], unique=False)

    op.create_table('fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('violation_code', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('violation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fines_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('tax_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('base_tax', sa.Integer(), nullable=False),
    sa.Column('swdkllj', sa.Integer(), nullable=False),
    sa.Column('admin_fee', sa.Integer(), nullable=False),
    sa.Column('fine_amount', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_records_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tax_record_id', sa.Integer(), nullable=True),
    sa.Column('fine_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=80), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('snap_token', sa.String(length=255), nullable=True),
    sa.Column('snap_redirect_url', sa.String(length=500), nullable=True),
    sa.Column('payment_type', sa.String(length=60), nullable=True),
    sa.Column('transaction_status', sa.String(length=40), nullable=False),
    sa.Column('fraud_status', sa.String(length=40), nullable=True),
    sa.Column('midtrans_transaction_id', sa.String(length=120), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], ),
    sa.ForeignKeyConstraint(['tax_record_id'], ['tax_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_order_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('tax_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_records_vehicle_id'))

    op.drop_table('tax_records')
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fines_vehicle_id'))

    op.drop_table('fines')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_user_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_plate_number'))
        batch_op.drop_index(batch_op.f('ix_vehicles_frame_number'))

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
