"""add stnk renewal applications

Revision ID: 71c3b17239ee
Revises: 4ebfef22dc14
Create Date: 2026-05-03 22:26:25.700619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c3b17239ee'
down_revision = '4ebfef22dc14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stnk_renewal_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('ktp_photo_path', sa.String(length=255), nullable=False),
    sa.Column('stnk_photo_path', sa.String(length=255), nullable=False),
    sa.Column('vehicle_photo_path', sa.String(length=255), nullable=False),
    sa.Column('physical_check_photo_path', sa.String(length=255), nullable=True),
    sa.Column('admin_fee', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stnk_renewal_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stnk_renewal_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stnk_renewal_applications_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stnk_renewal_application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_transactions_stnk_renewal_application_id',
            'stnk_renewal_applications',
            ['stnk_renewal_application_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_stnk_renewal_application_id', type_='foreignkey')
        batch_op.drop_column('stnk_renewal_application_id')

    with op.batch_alter_table('stnk_renewal_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stnk_renewal_applications_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_stnk_renewal_applications_user_id'))

    op.drop_table('stnk_renewal_applications')
    # ### end Alembic commands ###
